name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_PLASKMER }}
        run: |
          rm -rf .git
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git init
          git branch -m main
          git add .
          git commit -m "Force sync latest files"
          git push --force https://Jeffiq:$HF_TOKEN@huggingface.co/spaces/Jeffiq/Plaskmer main
