name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_PLASKMER }}
        # 🚨 CHANGE THE LINK BELOW to match your actual Hugging Face username and Space name
        run: git push --force https://Jeffiq:$HF_TOKEN@huggingface.co/spaces/Jeffiq/Plaskmer main
